"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { StockLogo, DataState, VendorTag, cls, sign, fmt, titleCaseLabel} from "../utils";
import { useLiveQuotes } from "../live-quotes-context";
import { useApiList } from "../hooks/useApiList";
import { useApiResource } from "../hooks/useApiResource";
import { firebaseAuth } from "../../firebase";
import { apiGet } from "../backend";
import type { NewsArticleDoc, CompanyDoc, WatchlistDoc, HoldingDoc } from "../types";
import { NEWS_TAGS } from "../types/news";
import { sectorFilterOptions, matchesSector } from "../sector-filter";
import { TickerAnalysisDrawer } from "../ticker-analysis-drawer";
import { StockScreenEmbed } from "../stock-panel";

const TABS = ["Live", "Premarket", "After Hours", "My names", "Macro"];

// Selected-tab styling — the app's active-pill language (brand fill + white),
// shared by BOTH the primary News/Announcement tabs and the inner sub-tabs so
// the selection colour is identical at every level.
const SEL_TAB = {
  background: "var(--brand)",
  color: "#fff",
  boxShadow: "0 1px 8px -2px rgba(0,0,0,.5)",
} as const;

/** One `announcement`-type row from ticker_ai_analysis (earnings-result AI read). */
interface AnnouncementDoc {
  ticker: string;
  companyName: string | null;
  summary: string;
  overallAssessment: string;
  keyDevelopments: string[];
  positiveFactors: string[];
  negativeFactors: string[];
  risks: string[];
  opportunities: string[];
  fundamentalImpact: string;
  priceImpact: string;
  shortTermImpact: string;
  mediumTermImpact: string;
  investorInterpretation: string;
  lastUpdatedAt: string;
  announcement?: {
    reportDate: string;
    epsActual: number | null;
    epsEstimate: number | null;
    surprisePct: number | null;
    revenueActual: number | null;
    revenueEstimate: number | null;
    verdict: "beat" | "miss" | "in-line" | "unknown";
  };
}

/** A titled bullet list — rendered only when it has items. */
function AnnList({ title, items, tone }: { title: string; items?: string[]; tone?: string }) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <div style={{ fontSize: ".64rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: ".05em", color: "var(--text-dim-solid)", marginBottom: 4 }}>{title}</div>
      <ul style={{ margin: 0, paddingLeft: 18, fontSize: ".78rem", lineHeight: 1.5 }}>
        {items.map((x, i) => <li key={i} className={tone}>{x}</li>)}
      </ul>
    </div>
  );
}

/** Earnings Announcement tab — expandable list of the per-ticker `announcement`
 *  AI reads (ticker_ai_analysis, generated by earnings-actuals.job as results
 *  land). Its own component so the fetch only runs when the tab is open. */
function EarningsAnnouncementsTab() {
  const { data: rows, loading } = useApiList<AnnouncementDoc>("/live/ticker-announcements?limit=100");
  const [openId, setOpenId] = useState<string | null>(null);
  return (
    <div style={{ padding: "14px 18px 18px" }}>
      <div className="card">
        <div className="card-h">
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <h3>Earnings Announcement</h3><VendorTag v={["polygon", "fmp"]} />
          </div>
          <span style={{ fontSize: ".72rem", color: "var(--text-dim-solid)" }}>
            {rows.length} AI {rows.length === 1 ? "analysis" : "analyses"}
          </span>
        </div>
        <div className="card-b" style={{ padding: 0, maxHeight: "none" }}>
          {rows.length === 0 ? (
            <div style={{ padding: "40px 18px", textAlign: "center" }}>
              <DataState loading={loading} label="No earnings announcements yet — an AI analysis is added here each time a tracked company reports (premarket & after-hours)." />
            </div>
          ) : rows.map((r) => {
            const a = r.announcement;
            const id = `${r.ticker}_${a?.reportDate ?? r.lastUpdatedAt}`;
            const isOpen = openId === id;
            const vClass = a?.verdict === "beat" ? "up" : a?.verdict === "miss" ? "down" : "";
            return (
              <div key={id} style={{ borderBottom: "1px solid var(--border-soft)" }}>
                <button
                  onClick={() => setOpenId(isOpen ? null : id)}
                  style={{ width: "100%", display: "flex", alignItems: "center", gap: 10, padding: "11px 14px", background: "none", border: 0, cursor: "pointer", textAlign: "left", color: "inherit" }}>
                  <StockLogo sym={r.ticker} size={26} />
                  <div style={{ minWidth: 0, flex: 1 }}>
                    <span className="tkr" style={{ display: "block" }}>{r.ticker} <small style={{ color: "var(--text-dim-solid)" }}>{r.companyName ?? ""}</small></span>
                    <div style={{ fontSize: ".74rem", color: "var(--text-dim-solid)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{r.summary}</div>
                  </div>
                  {a?.verdict && a.verdict !== "unknown" && (
                    <span className="pill" style={{ textTransform: "capitalize", flexShrink: 0 }}>
                      <span className={vClass}>{a.verdict}{a.surprisePct != null ? ` ${sign(a.surprisePct)}` : ""}</span>
                    </span>
                  )}
                  <span style={{ fontSize: ".7rem", color: "var(--text-dim-solid)", flexShrink: 0, minWidth: 76, textAlign: "right" }}>{a?.reportDate ?? ""}</span>
                  <span style={{ fontSize: ".7rem", color: "var(--text-dim-solid)", flexShrink: 0 }}>{isOpen ? "▲" : "▼"}</span>
                </button>
                {isOpen && (
                  <div style={{ padding: "2px 16px 16px 50px", display: "flex", flexDirection: "column", gap: 12 }}>
                    {(r.overallAssessment || r.summary) && <p style={{ fontSize: ".82rem", lineHeight: 1.5, margin: 0 }}>{r.overallAssessment || r.summary}</p>}
                    {a && (
                      <div style={{ display: "flex", gap: 16, flexWrap: "wrap", fontSize: ".74rem", color: "var(--text-dim-solid)" }}>
                        {a.epsActual != null && <span>EPS <b style={{ color: "var(--text-hi)" }}>{a.epsActual}</b>{a.epsEstimate != null ? ` vs est ${a.epsEstimate}` : ""}</span>}
                        {a.surprisePct != null && <span>Surprise <b className={vClass}>{sign(a.surprisePct)}</b></span>}
                        {a.revenueActual != null && <span>Rev <b style={{ color: "var(--text-hi)" }}>{fmt(a.revenueActual)}</b>{a.revenueEstimate != null ? ` vs ${fmt(a.revenueEstimate)}` : ""}</span>}
                      </div>
                    )}
                    <AnnList title="Key developments" items={r.keyDevelopments} />
                    <AnnList title="Positives" items={r.positiveFactors} tone="up" />
                    <AnnList title="Negatives" items={r.negativeFactors} tone="down" />
                    <AnnList title="Risks" items={r.risks} />
                    <AnnList title="Opportunities" items={r.opportunities} />
                    {(r.fundamentalImpact || r.priceImpact || r.shortTermImpact || r.mediumTermImpact) && (
                      <div style={{ fontSize: ".78rem", display: "flex", flexDirection: "column", gap: 6, lineHeight: 1.5 }}>
                        {r.fundamentalImpact && <div><b>Fundamental impact:</b> {r.fundamentalImpact}</div>}
                        {r.priceImpact && <div><b>Price impact:</b> {r.priceImpact}</div>}
                        {r.shortTermImpact && <div><b>Short term:</b> {r.shortTermImpact}</div>}
                        {r.mediumTermImpact && <div><b>Medium term:</b> {r.mediumTermImpact}</div>}
                      </div>
                    )}
                    <div style={{ fontSize: ".64rem", color: "var(--text-dim-solid)" }}>AI-generated · not investment advice · updated {String(r.lastUpdatedAt).slice(0, 16).replace("T", " ")}</div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// Market-cap tiers derived from companies.marketCap (raw USD). Used to filter
// the feed by the size of the company each news item is about.
const CAP_TIERS = ["All", "Mega", "Large", "Mid", "Small", "Micro"];
/** Compact market cap for the feed's left column — $1.2T / $340B / $8.4B / $720M. */
function fmtMcap(mc: number): string {
  if (mc >= 1e12) return `$${(mc / 1e12).toFixed(1)}T`;
  if (mc >= 1e9) return `$${(mc / 1e9).toFixed(mc >= 10e9 ? 0 : 1)}B`;
  if (mc >= 1e6) return `$${(mc / 1e6).toFixed(0)}M`;
  return `$${Math.round(mc).toLocaleString()}`;
}

function capTier(mc: number | null | undefined): string | null {
  if (mc == null) return null;
  if (mc >= 200e9) return "Mega";
  if (mc >= 10e9) return "Large";
  if (mc >= 2e9) return "Mid";
  if (mc >= 300e6) return "Small";
  return "Micro";
}

function catCol(c: string | null): string {
  if (c === "earnings") return "var(--warn)";
  if (c === "merger") return "var(--ai)";
  if (c === "company") return "var(--brand-2)";
  return "var(--text-dim-solid)";
}
function catLabel(c: string | null): string {
  if (c === "earnings") return "Earnings";
  if (c === "merger") return "M&A";
  if (c === "company") return "Company";
  return "Macro";
}

/**
 * The story-type chip's own filter key.
 *
 * A card carries TWO chips and they are not the same thing: `tag` is the
 * subject of the story (Earnings, Product & Launches, …) and drives the
 * Category filter; `category` is the KIND of story (Company, Macro, Earnings,
 * M&A) and is what the pill under the logo shows. Only the first was
 * filterable, so the pill was a label you could read and not act on.
 *
 * Normalised the same way catLabel resolves it — anything that is not one of
 * the three known values is "macro" — so the filter and the chip can never
 * disagree about which bucket a story is in.
 */
const CAT_KEYS = ["earnings", "merger", "company", "macro"] as const;
function catKey(c: string | null): string {
  return c === "earnings" || c === "merger" || c === "company" ? c : "macro";
}

function etHour(iso: string): number {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: "America/New_York", hour: "numeric", minute: "numeric", hour12: false,
  }).formatToParts(new Date(iso));
  const h = Number(parts.find(p => p.type === "hour")?.value ?? 12);
  const m = Number(parts.find(p => p.type === "minute")?.value ?? 0);
  return h + m / 60;
}
function etTimeLabel(iso: string): string {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: "America/New_York", hour: "numeric", minute: "2-digit", hour12: true,
  }).formatToParts(new Date(iso));
  const hour = parts.find(p => p.type === "hour")?.value ?? "12";
  const minute = parts.find(p => p.type === "minute")?.value ?? "00";
  const dayPeriod = (parts.find(p => p.type === "dayPeriod")?.value ?? "AM").toLowerCase()[0];
  return `${hour}:${minute}${dayPeriod}`;
}

/* ── Feed item ── the logo filters the feed by that ticker; the body opens the source article. */
function FeedItem({ item, i, total, onTicker, onAnalysis, onTag, onCat, activeTag, activeCat, marketCap, livePct }: {
  item: NewsArticleDoc; i: number; total: number; onTicker: (ticker: string) => void;
  onAnalysis: (ticker: string) => void;
  /* Both chips on the card are controls, not labels: clicking one filters the
     feed to it, clicking it again clears that filter. The dropdowns above hold
     the same state, so the two stay in step. */
  onTag: (tag: string) => void;
  onCat: (cat: string) => void;
  /** The filter currently in force, so the chip can show it is the active one. */
  activeTag: string;
  activeCat: string;
  /** Raw USD market cap from the ticker's companies doc; null when unsynced. */
  marketCap?: number | null;
  /** Live %change for the ticker, from the app-wide shared quote poll. */
  livePct?: number | null;
}) {
  return (
    <div
      style={{
        display: "flex", gap: 12, padding: "12px 0",
        borderBottom: i < total - 1 ? "1px solid var(--border-soft)" : "none",
      }}
    >
      <div style={{ flexShrink: 0, width: 90, display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 5 }}>
        <button
          onClick={() => onTicker(item.ticker)}
          title={`Filter the feed by ${item.ticker}`}
          style={{ all: "unset", cursor: "pointer", borderRadius: 6 }}
        >
          <StockLogo sym={item.ticker} size={28} />
        </button>
        <button
          className={`pill lf-chip${activeCat === catKey(item.category) ? " on" : ""}`}
          style={{ background: "var(--surface-3)", color: catCol(item.category) }}
          onClick={() => onCat(catKey(item.category))}
          title={activeCat === catKey(item.category)
            ? "Showing this type only — click to clear"
            : `Show only ${catLabel(item.category)} stories`}
        >{catLabel(item.category)}</button>
        <div className="mono" style={{ fontSize: ".66rem", color: "var(--text-dim-solid)" }}>{etTimeLabel(item.publishedAt)}</div>
        {/* Market cap + LIVE %change for the story's ticker, under the time.
            Both are omitted rather than shown as "—" when unavailable, so the
            column stays compact for tickers the universe hasn't synced. */}
        {marketCap != null && (
          <div className="mono" style={{ fontSize: ".64rem", color: "var(--text-dim-solid)" }}>
            {fmtMcap(marketCap)}
          </div>
        )}
        {livePct != null && (
          <div className={`mono ${cls(livePct)}`} style={{ fontSize: ".66rem", fontWeight: 700 }}>
            {sign(livePct)}
          </div>
        )}
      </div>
      <a
        href={item.url} target="_blank" rel="noreferrer"
        style={{ flex: 1, minWidth: 0, textDecoration: "none", color: "inherit", borderRadius: 8, display: "flex", gap: 10 }}
      >
        <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: ".88rem", color: "var(--text)" }}>
          {/* Category ahead of the ticker: it answers "what kind of story is
              this" before the reader parses the headline. Colour comes from the
              same --chip token the old filter chips used, so a category reads
              identically wherever it appears. */}
          <span
            className={`row-tag lf-chip${activeTag === (item.tag ?? "other") ? " on" : ""}`}
            data-tag={item.tag ?? "other"}
            role="button"
            tabIndex={0}
            /* Inside the <a> that opens the source article, so the navigation
               has to be suppressed — the same treatment the ticker below gets. */
            onClick={e => { e.preventDefault(); e.stopPropagation(); onTag(item.tag ?? "other"); }}
            onKeyDown={e => {
              if (e.key !== "Enter" && e.key !== " ") return;
              e.preventDefault(); e.stopPropagation(); onTag(item.tag ?? "other");
            }}
            title={activeTag === (item.tag ?? "other")
              ? "Showing this category only — click to clear"
              : `Show only ${NEWS_TAGS.find(t => t.key === (item.tag ?? "other"))?.label ?? "Other"} stories`}
          >
            {NEWS_TAGS.find(t => t.key === (item.tag ?? "other"))?.label ?? "Other"}
          </span>
          <b
            onClick={e => { e.preventDefault(); onTicker(item.ticker); }}
            style={{ cursor: "pointer" }}
            title={`Filter the feed by ${item.ticker}`}
          >{item.ticker}</b> {item.headline}
        </div>
        {item.summary && (
          <div style={{ fontSize: ".78rem", color: "var(--text-dim-solid)", borderLeft: `2px solid ${catCol(item.category)}55`, paddingLeft: 9, marginTop: 5 }}>
            {item.summary}
          </div>
        )}
        <div style={{ marginTop: 6, display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap" }}>
          <span style={{ fontSize: ".68rem", color: "var(--brand-2)", fontWeight: 600 }}>
            {item.source ? `Read at ${item.source}` : "Read source"} →
          </span>
          {item.vendor && (
            <span className="pill" style={{ fontSize: ".56rem", background: "var(--surface-3)", color: "var(--text-dim-solid)", textTransform: "uppercase", letterSpacing: ".03em" }}>
              via {item.vendor}
            </span>
          )}
          {item.sentiment && (
            <span className="pill" style={{ fontSize: ".56rem", textTransform: "capitalize", background: "var(--surface-3)", color: item.sentiment === "positive" ? "var(--up)" : item.sentiment === "negative" ? "var(--down)" : "var(--text-dim-solid)" }}>
              {item.sentiment}
            </span>
          )}
          {/* The row is wrapped in an <a> to the article, so this must stop the
              click reaching it — otherwise opening the analysis also navigates
              away to the publisher. */}
          <button
            className="feed-analysis-btn"
            onClick={e => { e.preventDefault(); e.stopPropagation(); onAnalysis(item.ticker); }}
            title={`AI analysis for ${item.ticker}`}
          >
            ◆ Analysis
          </button>
        </div>
        </div>
        {item.imageUrl && (
          <img
            src={item.imageUrl}
            alt=""
            loading="lazy"
            style={{ flexShrink: 0, width: 84, height: 84, objectFit: "cover", borderRadius: 8, background: "var(--surface-3)" }}
            onError={e => { (e.currentTarget as HTMLImageElement).style.display = "none"; }}
          />
        )}
      </a>
    </div>
  );
}

/* ── Main commentary / Live Feed screen ── */
// ── SCANX market scans (Most Active / Biggest %) ────────────────────────────
interface ScanItem { ticker: string; name: string | null; pctChange: number | null; price?: number | null; volume?: number | null; rvol?: number | null; }
interface SectorGroup { sector: string; items: ScanItem[]; }
interface BiggestPctScan { generatedAt: string; gainers: SectorGroup[]; losers: SectorGroup[]; }
interface MostActiveScan { generatedAt: string; byVolume: SectorGroup[]; byRelVolume: SectorGroup[]; }

const scanTime = (iso?: string) =>
  iso ? new Date(iso).toLocaleString(undefined, { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "";

/** One sector-categorised scan section — a coloured heading then one line per
 *  sector: "Sector: TICKER (value), …" (the SCANX layout). */
/**
 * Stock-detail tray for the scan tabs — the same drawer Movers opens, so a
 * ticker behaves identically wherever it is clicked.
 */
function ScanTray({ sym, onClose }: { sym: string; onClose: () => void }) {
  return (
    <>
      <div className="scrim" onClick={onClose} />
      <div className="stock-side-drawer">
        <div className="drawer-h" style={{ paddingTop: 14, paddingBottom: 14 }}>
          <StockLogo sym={sym} size={32} />
          <div style={{ flex: 1 }}>
            <div style={{ fontFamily: "var(--f-display)", fontWeight: 700, fontSize: "1rem", color: "var(--text-hi)" }}>
              {sym} · Stock Details
            </div>
            <div style={{ fontSize: ".72rem", color: "var(--text-dim-solid)" }}>
              Full analysis · chart · technicals · peers
            </div>
          </div>
          <button className="closebtn" onClick={onClose}>✕</button>
        </div>
        <div className="drawer-b">
          <StockScreenEmbed initialSym={sym} />
        </div>
      </div>
    </>
  );
}

function ScanSection({ title, color, groups, render, onSelect }: {
  title: string; color: string; groups: SectorGroup[]; render: (it: ScanItem) => string;
  onSelect: (sym: string) => void;
}) {
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ fontWeight: 700, fontSize: ".8rem", color, marginBottom: 6 }}>{title}</div>
      {(!groups || groups.length === 0) ? (
        <div style={{ fontSize: ".78rem", color: "var(--text-dim-solid)" }}>No data.</div>
      ) : groups.map((g) => (
        <div key={g.sector} style={{ fontSize: ".8rem", lineHeight: 2.1, display: "flex", flexWrap: "wrap", alignItems: "center", gap: "2px 4px" }}>
          <span style={{ color: "var(--text-dim-solid)", marginRight: 2 }}>{titleCaseLabel(g.sector)}:</span>
          {/* Each ticker is a real button with its logo — these used to be inert
              bold text, so a name you spotted in the scan could not be opened
              without going to another screen and searching for it. */}
          {g.items.map((it) => (
            <button
              key={it.ticker}
              type="button"
              className="scan-chip"
              onClick={() => onSelect(it.ticker)}
              title={`Open ${it.ticker} details`}
            >
              <StockLogo sym={it.ticker} size={15} />
              <b>{it.ticker}</b>
              <span className={cls(it.pctChange ?? 0)}>({render(it)})</span>
            </button>
          ))}
        </div>
      ))}
    </div>
  );
}

/** Most Active tab — top volume + top relative volume, by sector. */
function MostActiveTab() {
  const { data, loading } = useApiResource<MostActiveScan>("/live/scan/most-active");
  const [sel, setSel] = useState<string | null>(null);
  return (
    <div style={{ padding: "14px 18px 18px" }}>
      <div className="card">
        <div className="card-h">
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}><h3>Today&apos;s most active stocks</h3><VendorTag v="polygon" /></div>
          {data?.generatedAt && <span style={{ fontSize: ".7rem", color: "var(--text-dim-solid)" }}>as of {scanTime(data.generatedAt)}</span>}
        </div>
        <div className="card-b" style={{ maxHeight: "none" }}>
          {!data ? <DataState loading={loading} label="Generating scan…" /> : (
            <>
              <ScanSection title="Today's top 20 volume" color="var(--text-hi)" groups={data.byVolume} onSelect={setSel}
                render={(it) => `${it.volume != null ? (it.volume / 1e6).toFixed(2) + " mln" : "—"} ${sign(it.pctChange ?? 0)}`} />
              <ScanSection title="Today's top 20 relative volume (current vs 1-month avg daily volume)" color="var(--text-hi)" groups={data.byRelVolume} onSelect={setSel}
                render={(it) => `${it.rvol != null ? it.rvol.toFixed(2) + "x" : "—"} ${sign(it.pctChange ?? 0)}`} />
            </>
          )}
        </div>
      </div>
      {sel && <ScanTray sym={sel} onClose={() => setSel(null)} />}
    </div>
  );
}

/** Biggest % tab — top 20 gainers + top 20 losers, by sector. */
function BiggestPctTab() {
  const { data, loading } = useApiResource<BiggestPctScan>("/live/scan/biggest-pct");
  const [sel, setSel] = useState<string | null>(null);
  return (
    <div style={{ padding: "14px 18px 18px" }}>
      <div className="card">
        <div className="card-h">
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}><h3>Today&apos;s biggest % gainers / losers</h3><VendorTag v="polygon" /></div>
          {data?.generatedAt && <span style={{ fontSize: ".7rem", color: "var(--text-dim-solid)" }}>as of {scanTime(data.generatedAt)}</span>}
        </div>
        <div className="card-b" style={{ maxHeight: "none" }}>
          {!data ? <DataState loading={loading} label="Generating scan…" /> : (
            <>
              <ScanSection title="Today's top 20 % gainers" color="var(--up)" groups={data.gainers} onSelect={setSel}
                render={(it) => `${it.price != null ? it.price.toFixed(2) : "—"} ${sign(it.pctChange ?? 0)}`} />
              <ScanSection title="Today's top 20 % losers" color="var(--down)" groups={data.losers} onSelect={setSel}
                render={(it) => `${it.price != null ? it.price.toFixed(2) : "—"} ${sign(it.pctChange ?? 0)}`} />
            </>
          )}
        </div>
      </div>
      {sel && <ScanTray sym={sel} onClose={() => setSel(null)} />}
    </div>
  );
}

// ── Weekly / Monthly summary ────────────────────────────────────────────────
type GlanceSentiment = "bullish" | "bearish" | "neutral" | "mixed";
interface GlanceDoc {
  period: "weekly" | "monthly";
  periodKey: string;
  periodStart: string;
  periodEnd: string;
  generatedAt: string;
  sourceCount: number;
  model: string;
  marketTone: string;
  sentiment: GlanceSentiment;
  keyThemes: string[];
  biggestEarnings: string[];
  notableMovers: string[];
  summary: string;
}
interface GlanceResponse { generating: boolean; items: GlanceDoc[]; }

/** Sentiment styling for the glance digests — colour, a friendly label, and a
 *  glyph so each period reads at a glance instead of as a wall of grey text. */
const SENT: Record<GlanceSentiment, { color: string; label: string; icon: string }> = {
  bullish: { color: "var(--up)",             label: "Bullish", icon: "📈" },
  bearish: { color: "var(--down)",           label: "Bearish", icon: "📉" },
  mixed:   { color: "var(--warn)",           label: "Mixed",   icon: "🔀" },
  neutral: { color: "var(--text-dim-solid)", label: "Neutral", icon: "➖" },
};

/** Engaging replacement for the plain uppercase-bullet AnnList inside a glance
 *  digest: each item becomes a soft, accent-tinted chip with a colour dot, so
 *  themes / earnings / movers scan as tags rather than a dense list. */
function GlanceChips({ title, icon, items, color }: {
  title: string; icon: string; items?: string[]; color: string;
}) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", gap: 7, marginBottom: 9 }}>
        <span aria-hidden style={{ fontSize: ".9rem", lineHeight: 1 }}>{icon}</span>
        <span style={{ fontSize: ".68rem", fontWeight: 700, textTransform: "uppercase", letterSpacing: ".07em", color: "var(--text-dim-solid)" }}>{title}</span>
      </div>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>
        {items.map((x, i) => (
          <span key={i} style={{
            display: "inline-flex", alignItems: "center", gap: 8, maxWidth: "100%",
            fontSize: ".78rem", lineHeight: 1.45, color: "var(--text)",
            background: `color-mix(in srgb, ${color} 9%, var(--surface-2))`,
            border: `1px solid color-mix(in srgb, ${color} 24%, var(--border-soft))`,
            borderRadius: 9, padding: "6px 11px",
          }}>
            <span style={{ width: 6, height: 6, borderRadius: "50%", background: color, flexShrink: 0 }} />
            <span>{x}</span>
          </span>
        ))}
      </div>
    </div>
  );
}

/** "August 2026" (monthly) or "Week of Aug 24 – 30, 2026" (weekly). All UTC so
 *  the label matches the period keys the backend wrote. */
function glanceLabel(d: GlanceDoc): string {
  const s = new Date(d.periodStart);
  if (d.period === "monthly") {
    return s.toLocaleDateString(undefined, { month: "long", year: "numeric", timeZone: "UTC" });
  }
  const e = new Date(Date.parse(d.periodEnd) - 24 * 3600 * 1000); // inclusive last day
  const sM = s.toLocaleDateString(undefined, { month: "short", day: "numeric", timeZone: "UTC" });
  const eM = e.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" });
  return `Week of ${sM} – ${eM}`;
}

/** One market-wide digest per period, newest first, as an expandable list so
 *  users can open past periods. The current period is generated on demand and
 *  the tab polls until it appears; past periods are read straight from cache. */
function GlanceTab({ period, heading }: { period: "weekly" | "monthly"; heading: string }) {
  // Generation is synchronous server-side: the first view of a stale period
  // waits (~seconds) while `loading` is true, then this returns the full digest.
  const { data, loading } = useApiResource<GlanceResponse>(`/live/glance/${period}`);
  const [openKey, setOpenKey] = useState<string | null>(null); // null = default to first
  const items = data?.items ?? [];
  const openEff = openKey === null ? (items[0]?.periodKey ?? null) : (openKey === "" ? null : openKey);

  return (
    <div style={{ padding: "14px 18px 18px" }}>
      <div className="card">
        <div className="card-h">
          <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
            <h3>{heading}</h3>
            <span style={{ fontSize: ".58rem", fontWeight: 700, letterSpacing: ".04em", padding: "2px 5px", borderRadius: 4, background: "var(--ai)", color: "#fff" }}>AI</span>
          </div>
          <span style={{ fontSize: ".72rem", color: "var(--text-dim-solid)" }}>
            {items.length} {items.length === 1 ? "period" : "periods"}
          </span>
        </div>
        <div className="card-b" style={{ padding: 0, maxHeight: "none" }}>
          {items.length === 0 ? (
            <div style={{ padding: "40px 18px", textAlign: "center" }}>
              <DataState loading={loading}
                label="No summaries yet — a market-wide digest is built from the period's ticker analyses on first view." />
            </div>
          ) : items.map((it) => {
            const isOpen = it.periodKey === openEff;
            const isCurrent = Date.parse(it.periodEnd) > Date.now();
            const noContent = !it.marketTone && it.keyThemes.length === 0 && it.notableMovers.length === 0;
            const sc = SENT[it.sentiment];
            return (
              <div key={it.periodKey} style={{
                borderBottom: "1px solid var(--border-soft)",
                // Soft sentiment-tinted left rail + wash, brighter when the
                // period is open so the eye lands on the expanded digest.
                borderLeft: `3px solid ${isOpen ? sc.color : "transparent"}`,
                background: isOpen ? `color-mix(in srgb, ${sc.color} 5%, transparent)` : "transparent",
                transition: "background .18s ease, border-color .18s ease",
              }}>
                <button
                  onClick={() => setOpenKey(isOpen ? "" : it.periodKey)}
                  style={{ width: "100%", display: "flex", alignItems: "center", gap: 12, padding: "12px 14px", background: "none", border: 0, cursor: "pointer", textAlign: "left", color: "inherit" }}>
                  {/* Sentiment glyph in a soft tinted tile — an at-a-glance mood
                      cue so each period leads with colour, not grey text. */}
                  <span aria-hidden style={{
                    width: 34, height: 34, flexShrink: 0, display: "grid", placeItems: "center",
                    fontSize: "1rem", borderRadius: 10,
                    background: `color-mix(in srgb, ${sc.color} 15%, var(--surface-2))`,
                    border: `1px solid color-mix(in srgb, ${sc.color} 28%, var(--border-soft))`,
                  }}>{sc.icon}</span>
                  <div style={{ minWidth: 0, flex: 1 }}>
                    {/* Deliberately NOT .tkr. That class is the fixed-width
                        ticker-symbol style — `width: 52px` with
                        `.tkr small { display: block }` — which is right for
                        "NVDA" and wrong for a date range: it boxed
                        "Week of Aug 24 – Aug 30, 2026" into 52px and pushed
                        "· current" onto its own line. Plain styles here, with
                        nowrap so the range never splits at its en dash. */}
                    <span style={{
                      display: "block", fontSize: ".84rem", fontWeight: 700, color: "var(--text-hi)",
                      whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis",
                    }}>
                      {glanceLabel(it)}
                      {isCurrent && (
                        <small style={{
                          marginLeft: 7, fontSize: ".58rem", fontWeight: 700, letterSpacing: ".05em",
                          textTransform: "uppercase", color: "var(--up)", verticalAlign: "middle",
                          background: "color-mix(in srgb, var(--up) 15%, transparent)",
                          borderRadius: 5, padding: "2px 6px",
                        }}>● Live</small>
                      )}
                    </span>
                    <div style={{ fontSize: ".76rem", color: "var(--text-dim-solid)", lineHeight: 1.4, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", marginTop: 1 }}>
                      {it.marketTone || it.summary}
                    </div>
                  </div>
                  {!noContent && (
                    <span style={{
                      flexShrink: 0, display: "inline-flex", alignItems: "center", gap: 6,
                      fontSize: ".7rem", fontWeight: 700, color: sc.color, borderRadius: 20, padding: "4px 11px",
                      background: `color-mix(in srgb, ${sc.color} 13%, transparent)`,
                      border: `1px solid color-mix(in srgb, ${sc.color} 30%, transparent)`,
                    }}>
                      <span style={{ width: 6, height: 6, borderRadius: "50%", background: sc.color }} />
                      {sc.label}
                    </span>
                  )}
                  <span style={{ fontSize: ".7rem", color: "var(--text-dim-solid)", flexShrink: 0 }}>{isOpen ? "▲" : "▼"}</span>
                </button>
                {isOpen && (
                  <div style={{ padding: "4px 16px 18px 16px", display: "flex", flexDirection: "column", gap: 16 }}>
                    {/* Market tone as a lead line with a sentiment-coloured rail —
                        the headline read, not just another paragraph. */}
                    {it.marketTone && (
                      <p style={{
                        margin: 0, fontSize: ".92rem", lineHeight: 1.55, fontWeight: 600, color: "var(--text-hi)",
                        borderLeft: `3px solid ${sc.color}`, paddingLeft: 13,
                      }}>{it.marketTone}</p>
                    )}
                    {it.summary && <p style={{ fontSize: ".83rem", lineHeight: 1.6, margin: 0, color: "var(--text)" }}>{it.summary}</p>}
                    <GlanceChips title="Key themes"       icon="🎯" items={it.keyThemes}       color="var(--brand)" />
                    <GlanceChips title="Biggest earnings" icon="📊" items={it.biggestEarnings} color="var(--ai)" />
                    <GlanceChips title="Notable movers"   icon="🚀" items={it.notableMovers}   color={sc.color} />
                    <div style={{ fontSize: ".64rem", color: "var(--text-dim-solid)", display: "flex", alignItems: "center", gap: 7, flexWrap: "wrap", paddingTop: 10, borderTop: "1px solid var(--border-soft)" }}>
                      <span style={{ fontSize: ".55rem", fontWeight: 700, letterSpacing: ".04em", padding: "1px 5px", borderRadius: 4, background: "var(--ai)", color: "#fff" }}>AI</span>
                      Not investment advice · {it.sourceCount} {it.sourceCount === 1 ? "analysis" : "analyses"}
                      {it.generatedAt ? ` · generated ${String(it.generatedAt).slice(0, 16).replace("T", " ")}` : ""}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

export function CommentaryScreen() {
  const router = useRouter();
  const uid = firebaseAuth.currentUser?.uid ?? null;
  const { data: liveNews, loading: liveNewsLoading } = useApiList<NewsArticleDoc>("/market-data/news");
  const { data: companies, loading: companiesLoading } = useApiList<CompanyDoc>("/market-data/companies");
  // /market-data/filings-wire and /market-data/macro-regime were fetched here
  // only to fill the Filings wire and Market regime rail cards. With the rail
  // gone nothing on this screen reads them, so the two requests go too rather
  // than loading data that is never rendered. The macro-regime read still has a
  // home on the Macro & VIX screen.
  const [mainTab,       setMainTab]       = useState(0); // 0 = News, 1 = Announcement
  const [activeTab,     setActiveTab]     = useState(0);
  const [search,        setSearch]        = useState("");
  const [secFilter,     setSecFilter]     = useState("All");
  const [capFilter,     setCapFilter]     = useState("All");
  const [tagFilter,     setTagFilter]     = useState<string>("all");
  /* The story-type pill (Company / Macro / Earnings / M&A). See catKey. */
  const [catFilter,     setCatFilter]     = useState<string>("all");
  /* Default ON: ~26% of the feed is auto-generated 13F notes and listicles,
     mostly from defenseworld.net and Motley Fool syndication. */
  // The "Hide filler" toggle is gone: it defaulted ON and silently dropped
  // items tagged `filler` (auto-generated 13F notes, ranked-list clickbait),
  // so the feed never showed everything the backend had. Every item now
  // renders and the reader decides. `filler` is still written by the news job
  // and stays on NewsArticleDoc for anything that wants it later.
  /* Which ticker's rolling AI analysis is open. Read-only: the endpoint never
     triggers generation, so opening this cannot incur a model call. */
  const [analysisTicker, setAnalysisTicker] = useState<string | null>(null);
  const searchRef = useRef<HTMLInputElement>(null);

  const companyByTicker = new Map(companies.map(c => [c.ticker, c]));

  const [mySymbols, setMySymbols] = useState<Set<string>>(new Set());
  useEffect(() => {
    (async () => {
      if (!uid) return new Set<string>();
      const [w, p] = await Promise.all([
        apiGet<WatchlistDoc>("/api/watchlist").catch(() => ({ tickers: [] as string[] })),
        apiGet<{ holdings: HoldingDoc[] }>("/api/portfolio").catch(() => ({ holdings: [] as HoldingDoc[] })),
      ]);
      return new Set([...w.tickers, ...p.holdings.map(h => h.ticker)]);
    })().then(setMySymbols);
  }, [uid]);

  const symbolList = [...companies].filter(c => !!c.ticker).sort((a, b) => (b.marketCap ?? 0) - (a.marketCap ?? 0)).map(c => ({ s: c.ticker, n: c.name ?? c.ticker }));
  const topSymbols = symbolList.slice(0, 8).map(x => x.s);
  /* Plain free-text search — matches anywhere in the message (ticker / headline / summary). */
  const q = search.trim().toLowerCase();

  const sorted = [...liveNews].sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());
  const premarket  = sorted.filter(n => etHour(n.publishedAt) < 9.5);
  const afterHours = sorted.filter(n => etHour(n.publishedAt) >= 16);
  const macro      = sorted.filter(n => n.category !== "company");
  const myFeed     = sorted.filter(n => mySymbols.has(n.ticker));

  const tabFeed: NewsArticleDoc[] = (() => {
    if (activeTab === 1) return premarket;
    if (activeTab === 2) return afterHours;
    if (activeTab === 3) return myFeed;
    if (activeTab === 4) return macro;
    return sorted;
  })();

  // Sector dropdown uses the SAME unified option set as every other screen —
  // "All" + live GICS sectors + curated theme baskets — so filtering the feed
  // by company.sector (or by theme ticker membership) is uniform app-wide.
  const feedSectors = sectorFilterOptions(companies);
  const effSec = feedSectors.includes(secFilter) ? secFilter : "All";

  /* Filter the feed by the typed text + sector + market-cap (on top of the tab).
     Sector/cap are resolved from the companies doc for each item's ticker; an
     item whose ticker isn't in the companies collection is excluded once either
     of those filters is active (it can't be classified). */
  const displayFeed = tabFeed.filter(n => {
    if (q &&
      !((n.ticker ?? "").toLowerCase().includes(q) ||
        (n.headline ?? "").toLowerCase().includes(q) ||
        (n.summary ?? "").toLowerCase().includes(q))) return false;
    if (tagFilter !== "all" && (n.tag ?? "other") !== tagFilter) return false;
    if (catFilter !== "all" && catKey(n.category) !== catFilter) return false;
    if (effSec !== "All" || capFilter !== "All") {
      const c = companyByTicker.get(n.ticker);
      if (effSec !== "All" && !matchesSector(effSec, n.ticker, c?.sector)) return false;
      if (capFilter !== "All" && capTier(c?.marketCap) !== capFilter) return false;
    }
    return true;
  });

  /* Chip counts come from the feed BEFORE either chip filter is applied, so the
     numbers stay put when you select a chip — a count that collapsed to its
     own bucket the moment you clicked it would be useless for comparison.

     Both chip families are counted off the SAME base, so "Earnings (12)" under
     Category and "Company (80)" under Type are directly comparable rather than
     each being measured against a differently-filtered feed. */
  const [tagCounts, catCounts] = (() => {
    const base = tabFeed.filter(n => {
      if (q &&
        !((n.ticker ?? "").toLowerCase().includes(q) ||
          (n.headline ?? "").toLowerCase().includes(q) ||
          (n.summary ?? "").toLowerCase().includes(q))) return false;
      if (effSec !== "All" || capFilter !== "All") {
        const c = companyByTicker.get(n.ticker);
        if (effSec !== "All" && !matchesSector(effSec, n.ticker, c?.sector)) return false;
        if (capFilter !== "All" && capTier(c?.marketCap) !== capFilter) return false;
      }
      return true;
    });
    const tags: Record<string, number> = { all: base.length };
    const cats: Record<string, number> = { all: base.length };
    for (const n of base) {
      const t = n.tag ?? "other";
      tags[t] = (tags[t] ?? 0) + 1;
      const c = catKey(n.category);
      cats[c] = (cats[c] ?? 0) + 1;
    }
    return [tags, cats] as const;
  })();

  /* Collapse multi-ticker duplicates. Polygon tags one article to EVERY ticker
     it mentions, so the same story arrives once per ticker (an Alphabet piece
     gets tagged both GOOG and MSFT). In this aggregated feed we show it ONCE,
     keeping the ticker whose company name actually appears in the headline
     (so the Alphabet story keeps GOOG, not the incidental MSFT mention). */
  const feed = (() => {
    const byKey = new Map<string, NewsArticleDoc>();
    const order: string[] = [];
    const relevance = (n: NewsArticleDoc) => {
      const nm = companyByTicker.get(n.ticker)?.name?.split(/[\s,.]/)[0]?.toLowerCase();
      return nm && nm.length > 2 && (n.headline ?? "").toLowerCase().includes(nm) ? 1 : 0;
    };
    for (const n of displayFeed) {
      const key = n.url || n.id;
      const cur = byKey.get(key);
      if (!cur) { byKey.set(key, n); order.push(key); }
      else if (relevance(n) > relevance(cur)) byKey.set(key, n);
    }
    return order.map(k => byKey.get(k) as NewsArticleDoc);
  })();

  // LIVE %change for the tickers actually rendered in the feed, via the app-wide
  // shared poll — one timer for the whole app, so a story's %change here matches
  // the same ticker on the heatmap, movers and the stock drawer exactly.
  const feedQuotes = useLiveQuotes(feed.map(n => n.ticker).filter(Boolean));

  const feedLabel = (() => {
    if (activeTab === 0) return { title: "Intraday commentary", badge: <span className="live"><span className="dot" />Live · streaming</span> };
    if (activeTab === 1) return { title: "Pre-market · before 9:30a ET", badge: <span className="pill" style={{ background: "var(--surface-3)", color: "var(--brand-2)" }}>Pre-market</span> };
    if (activeTab === 2) return { title: "After hours · post 4:00p ET", badge: <span className="pill amc">After hours</span> };
    if (activeTab === 3) return { title: `My names · ${mySymbols.size} tracked`, badge: <span className="pill ai">Portfolio + Watchlist</span> };
    if (activeTab === 4) return { title: "Macro & rates", badge: <span className="pill" style={{ background: "var(--surface-3)", color: "var(--warn)" }}>Macro</span> };
    return { title: "Commentary", badge: null };
  })();


  return (
    <>
      {/* Primary tabs: News vs Earnings Announcement. Everything that used to be
          the Live Feed lives under News; Earnings Announcement will surface the
          per-ticker `announcement`-type AI reads (ticker_ai_analysis, generated
          when an earnings result lands). Placeholder until that's wired. */}
      <div className="page-head">
        <div className="tabs">
          <button className={`tab${mainTab === 0 ? " on" : ""}`} style={mainTab === 0 ? SEL_TAB : undefined} onClick={() => setMainTab(0)}>News</button>
          <button className={`tab${mainTab === 1 ? " on" : ""}`} style={mainTab === 1 ? SEL_TAB : undefined} onClick={() => setMainTab(1)}>Announcement</button>
          <button className={`tab${mainTab === 2 ? " on" : ""}`} style={mainTab === 2 ? SEL_TAB : undefined} onClick={() => setMainTab(2)}>Most Active</button>
          <button className={`tab${mainTab === 3 ? " on" : ""}`} style={mainTab === 3 ? SEL_TAB : undefined} onClick={() => setMainTab(3)}>Biggest %</button>
          <button className={`tab${mainTab === 4 ? " on" : ""}`} style={mainTab === 4 ? SEL_TAB : undefined} onClick={() => setMainTab(4)}>Weekly Summary</button>
          <button className={`tab${mainTab === 5 ? " on" : ""}`} style={mainTab === 5 ? SEL_TAB : undefined} onClick={() => setMainTab(5)}>Monthly Summary</button>
        </div>
      </div>

      {mainTab === 0 && (<>
      {/* The filter bar.
          Inline styles were doing the layout here, which meant it could not
          carry a media query — below roughly a laptop the six controls simply
          wrapped into a ragged pile, and on a phone the selects overflowed the
          screen. It is CSS now (.lf-* in iq.css): one row on a desktop, the
          search on its own line on a laptop, a two-column grid on a tablet and
          a single stacked column with aligned labels on a phone. */}
      <div className="lf-filters">
        <div className="lf-filters-in">
          <div className="lf-search">
            <input
              ref={searchRef}
              className="mv-sel"
              placeholder="Search the feed — ticker, company or keyword…"
              value={search}
              onChange={e => setSearch(e.target.value)}
              autoComplete="off"
            />
          </div>
          {/* View (was the Live / Premarket / After Hours tab row) and Category
              (was the chip row) are dropdowns now, so every filter on this
              screen reads the same way. Counts stay on the chip options — the
              number is the reason to pick one. */}
          <label className="lf-f">
            <span>View</span>
            <select className="mv-sel" value={activeTab} onChange={e => setActiveTab(Number(e.target.value))}>
              {TABS.map((t, i) => <option key={t} value={i}>{t}</option>)}
            </select>
          </label>
          {/* The card's headline chip — Earnings, Product & Launches, … */}
          <label className="lf-f">
            <span>Category</span>
            <select className="mv-sel" value={tagFilter} onChange={e => setTagFilter(e.target.value)}>
              <option value="all">All ({tagCounts.all ?? 0})</option>
              {NEWS_TAGS.filter(t => (tagCounts[t.key] ?? 0) > 0).map(t => (
                <option key={t.key} value={t.key}>{t.label} ({tagCounts[t.key] ?? 0})</option>
              ))}
            </select>
          </label>
          {/* The pill under the logo — Company, Macro, Earnings, M&A. Same
              options the chips themselves set when clicked. */}
          <label className="lf-f">
            <span>Type</span>
            <select className="mv-sel" value={catFilter} onChange={e => setCatFilter(e.target.value)}>
              <option value="all">All ({catCounts.all ?? 0})</option>
              {CAT_KEYS.filter(k => (catCounts[k] ?? 0) > 0).map(k => (
                <option key={k} value={k}>{catLabel(k === "macro" ? null : k)} ({catCounts[k] ?? 0})</option>
              ))}
            </select>
          </label>
          <label className="lf-f">
            <span>Sector</span>
            <select className="mv-sel" value={effSec} onChange={e => setSecFilter(e.target.value)}>
              {feedSectors.map(s => <option key={s} value={s}>{titleCaseLabel(s)}</option>)}
            </select>
          </label>
          <label className="lf-f">
            <span>Market cap</span>
            <select className="mv-sel" value={capFilter} onChange={e => setCapFilter(e.target.value)}>
              {CAP_TIERS.map(c => <option key={c} value={c}>{c}</option>)}
            </select>
          </label>
          {/* One reset for everything, shown only when something is actually
              filtered — with six controls (and two of them now settable by
              clicking a chip on a card) it is easy to lose track of why the
              feed looks empty. */}
          {(search.trim() || tagFilter !== "all" || catFilter !== "all" || effSec !== "All" || capFilter !== "All") && (
            <button
              className="chip lf-clear"
              onClick={() => { setSearch(""); setTagFilter("all"); setCatFilter("all"); setSecFilter("All"); setCapFilter("All"); }}
              title="Clear every filter"
            >
              Clear
              {/* An inline SVG, not a "✕" character: the glyph renders at a
                  different weight and baseline in every font the theme picker
                  can swap in, and it sat visibly low next to the label. */}
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" aria-hidden="true">
                <path d="M5 5l14 14M19 5L5 19" />
              </svg>
            </button>
          )}
        </div>
      </div>

      <div style={{ padding: "0 18px 18px" }}>


        <div className="dash">

          {/* Full width: the right rail that used to sit beside this (Before
              the Bell, After the Close, Filings wire, Market regime) is gone,
              so the feed takes all 12 columns instead of 8. Still a flex column
              so the feed card grows to fill the row. */}
          <div className="col-12" style={{ display: "flex", flexDirection: "column", gap: 14 }}>
            {/* Quick lookup — tap a ticker to add it to the feed filter. Sits
                at the TOP of the column; the feed card below flex-fills. */}
            <div className="card" style={{ flexShrink: 0 }}>
              <div className="card-h">
                <div style={{ display: "flex", alignItems: "center", gap: 6 }}><h3>{activeTab === 3 ? "Tracked names" : "Quick filter"}</h3><VendorTag v="polygon" /></div>
              </div>
              <div className="card-b" style={{ paddingTop: 8, display: "flex", gap: 6, flexWrap: "wrap" }}>
                {(activeTab === 3 ? [...mySymbols] : topSymbols).length === 0 ? (
                  <DataState loading={activeTab === 3 ? false : companiesLoading} label={activeTab === 3 ? "No tracked names yet." : "No live companies synced yet."} />
                ) : (activeTab === 3 ? [...mySymbols] : topSymbols).map(sym => (
                  <button
                    key={sym}
                    className={`chip${search.trim().toUpperCase() === sym.toUpperCase() ? " on" : ""}`}
                    onClick={() => setSearch(search.trim().toUpperCase() === sym.toUpperCase() ? "" : sym)}
                  >{sym}</button>
                ))}
              </div>
            </div>

            <div className="card" style={{ flex: 1, minHeight: 0, display: "flex", flexDirection: "column" }}>
              <div className="card-h">
                <div style={{ display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" }}><h3>{feedLabel.title}{q ? ` · “${search.trim()}”` : ""}</h3><VendorTag v={["polygon", "fmp"]} /></div>
                {feedLabel.badge}
              </div>
              <div className="card-b" style={{ paddingTop: 2, flex: 1, minHeight: 0, overflowY: "auto" }}>
                {feed.length === 0 ? (
                  <DataState loading={liveNewsLoading} label={
                    q
                      ? `No matches for “${search.trim()}” in this tab.`
                      : activeTab === 3
                        ? (uid ? "No live news matches your portfolio or watchlist names right now." : "Sign in and add names to your watchlist or portfolio to see this feed.")
                        : "No live news items in this category right now."} />
                ) : feed.map((item, i) => (
                  <FeedItem
                    key={item.id}
                    item={item}
                    i={i}
                    total={feed.length}
                    onTicker={sym => setSearch(sym)}
                    onAnalysis={setAnalysisTicker}
                    /* Clicking the chip that is already filtering clears it, so
                       the chip is a toggle rather than a one-way trip that only
                       the dropdown can undo. */
                    onTag={t => setTagFilter(cur => (cur === t ? "all" : t))}
                    onCat={c => setCatFilter(cur => (cur === c ? "all" : c))}
                    activeTag={tagFilter}
                    activeCat={catFilter}
                    marketCap={companyByTicker.get(item.ticker)?.marketCap ?? null}
                    livePct={feedQuotes.get(item.ticker)?.pctChange ?? companyByTicker.get(item.ticker)?.pctChange ?? null}
                  />
                ))}
              </div>
            </div>
          </div>

        </div>
      </div>
      </>)}

      {mainTab === 1 && <EarningsAnnouncementsTab />}
      {mainTab === 2 && <MostActiveTab />}
      {mainTab === 3 && <BiggestPctTab />}
      {mainTab === 4 && <GlanceTab period="weekly" heading="Weekly summary" />}
      {mainTab === 5 && <GlanceTab period="monthly" heading="Monthly summary" />}

      {analysisTicker && (
        <TickerAnalysisDrawer sym={analysisTicker} onClose={() => setAnalysisTicker(null)} />
      )}
    </>
  );
}
